version: "3"

services:
  pg-master:
    image: docker.io/bitnami/postgresql:11
    ports:
      - '32768:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      POSTGRESQL_REPLICATION_MODE: "master"
      POSTGRESQL_REPLICATION_USER: "repl_user"
      POSTGRESQL_REPLICATION_PASSWORD: "repl_password"
      POSTGRESQL_USERNAME: "postgres"
      POSTGRESQL_PASSWORD: "my_password"
      POSTGRESQL_DATABASE: "my_database"
      ALLOW_EMPTY_PASSWORD: "yes"
  pg-slave:
    image: docker.io/bitnami/postgresql:11
    ports:
      - '32769:5432'
    depends_on:
      - pg-master
    environment:
      POSTGRESQL_REPLICATION_MODE: "slave"
      POSTGRESQL_REPLICATION_USER: "repl_user"
      POSTGRESQL_REPLICATION_PASSWORD: "repl_password"
      POSTGRESQL_MASTER_HOST: "pg-master"
      POSTGRESQL_PASSWORD: "my_password"
      POSTGRESQL_MASTER_PORT_NUMBER: "5432"
      ALLOW_EMPTY_PASSWORD: "yes"

  adminer:
    image: adminer
    restart: always
    ports:
      - 12510:8080
    deploy:
      resources:
        limits:
          memory: 1G
    logging:
      options:
        max-size: 10m
    depends_on:
      - pg-slave
  app:
    build:
      context: .
    ports:
      - "9000:8000"
    volumes:
      - "./app:/app"
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      ENV: "dev"
      MASTER_DB_USER: "postgres"
      MASTER_DB_PASSWORD: "my_password"
      MASTER_DB_HOST: "pg-master"
      MASTER_DB_PORT: "5432"
      SLAVE_DB_USER: "postgres"
      SLAVE_DB_PASSWORD: "my_password"
      SLAVE_DB_HOST: "pg-slave"
      SLAVE_DB_PORT: "5432"
    depends_on:
      - pg-slave
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "99:80"
    depends_on:
      - app

volumes:
  postgresql_master_data:
    driver: local