# Generated by Django 4.0 on 2021-12-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('IN_REVIEW', 'IN_REVIEW'), ('VALIDATED', 'VALIDATED'), ('DECLINED', 'DECLINED')], max_length=32)),
                ('id_document', models.ImageField(upload_to='')),
                ('selfie', models.ImageField(upload_to='')),
                ('document_type', models.CharField(choices=[('ID_CARD', 'ID_CARD'), ('DRIVER_LICENSE', 'DRIVER_LICENSE'), ('PASSPORT', 'PASSPORT')], max_length=32)),
                ('review', models.CharField(blank=True, max_length=512, null=True)),
                ('reviewer', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='users.user')),
            ],
        ),
    ]
