# Generated by Django 4.0 on 2021-12-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('DR', 'DRAFT'), ('SU', 'SUBMITTED'), ('IR', 'IN_REVIEW'), ('VF', 'VERIFIED'), ('ES', 'ESCALATED'), ('DC', 'DECLINED')], max_length=32),
        ),
    ]
