# Generated by Django 4.0 on 2021-12-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='id_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('DR', 'DRAFT'), ('SU', 'SUBMITTED'), ('IR', 'IN_REVIEW'), ('VF', 'VERIFIED'), ('ES', 'ESCALATED'), ('DC', 'DECLINED')], default='SU', max_length=32),
        ),
    ]
