# Generated by Django 4.0 on 2021-12-31 19:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('WV', 'WAIT_FOR_VALIDATION'), ('VA', 'VALIDATED'), ('PR', 'PROCESSED'), ('CA', 'CANCELED')], default='WV', max_length=6)),
                ('validation_code', models.CharField(blank=True, max_length=6)),
                ('transaction_id', models.CharField(max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PG', 'PROCESSING'), ('PR', 'PROCESSED'), ('FAILED', 'FAILED')], default='PG', max_length=6)),
                ('transaction_id', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
